### PR TITLE
fix: fix url for current rockspec

### PR DESCRIPTION
**Pull request by teto**
@alerque @Tieske

### CODE REVIEW

**Comment by teto** [comment]
I've just added older rockspecs

**Review by alerque — APPROVED** [review]
LGTM.

**Comment by alerque** [comment]
This is going to need a `1.0.0` tag in the repo similar to my comments on *iconv*.

**Comment by alerque** [comment]
This had the same download archive name vs. extracted directory name issue as *iconv*. I just fixed it via 832f6fd.

**Comment by Tieske** [comment]
just a general remark; I prefer to use the git-repo itself instead of an artifact, so using the "git+https://...." scheme

**Comment by alerque** [comment]
@Tieske Sure that works too (we do it on many of the other ones in this org) but doesn't that introduce a `git` dependency that LuaRocks needs to be able to call? As opposed to the 3 alternative http download agents it can use. Not a big deal probably, just a minor trade off.

**Pull request merged**
